import { Agent } from './agents';

// Personal Branding Team Agents
export const PERSONAL_BRANDING_AGENTS: Agent[] = [
  {
    id: 'agent-pb-001',
    name: 'Aria Martinez',
    role: 'Senior Brand Lead',
    category: 'Branding',
    specialization: 'Personal Brand Strategy',
    description: 'Elite personal branding specialist for C-suite executives, thought leaders, and entrepreneurs. 8+ years of experience building authority brands.',
    model: 'gpt-4-turbo',
    price_per_hour: 42,
    level: 9,
    rating: 4.9,
    total_reviews: 247,
    creator: '@BrandMaven',
    creator_type: 'community',
    tools: ['content_strategy', 'linkedin_optimizer', 'brand_analytics'],
    photo_url: 'https://i.pravatar.cc/150?img=47',
    tags: ['branding', 'strategy', 'positioning', 'executive'],
  },
  {
    id: 'agent-pb-002',
    name: 'The Color Oracle',
    role: 'RGB Psychology Expert',
    category: 'Branding',
    specialization: 'Color Psychology & Visual Identity',
    description: 'Specializes in using color psychology to create memorable, emotionally resonant brands. Expert in ensuring accessibility while maintaining aesthetic appeal.',
    model: 'claude-3-opus',
    price_per_hour: 38,
    level: 8,
    rating: 4.8,
    total_reviews: 189,
    creator: '@DesignGuru',
    creator_type: 'community',
    tools: ['color_analyzer', 'contrast_checker', 'brand_identity'],
    photo_url: 'https://i.pravatar.cc/150?img=32',
    tags: ['color-theory', 'visual-identity', 'psychology', 'accessibility'],
  },
  {
    id: 'agent-pb-003',
    name: 'Trend-Bot 2026',
    role: 'Viral Hook Specialist',
    category: 'Branding',
    specialization: 'Viral Content & Engagement',
    description: 'AI agent trained on 10M+ viral posts. Predicts trends before they peak and crafts hooks that drive engagement. Updated daily with latest platform algorithms.',
    model: 'gpt-4',
    price_per_hour: 45,
    level: 10,
    rating: 4.9,
    total_reviews: 312,
    creator: '@TrendHunter',
    creator_type: 'community',
    tools: ['trend_analyzer', 'ab_testing', 'engagement_optimizer', 'social_api'],
    photo_url: 'https://i.pravatar.cc/150?img=68',
    tags: ['viral', 'trends', 'engagement', 'social-media', 'algorithms'],
  },
  {
    id: 'agent-pb-004',
    name: 'Typo-Master',
    role: 'Readability & Typography Expert',
    category: 'Branding',
    specialization: 'Typography & Content Flow',
    description: 'Ensures your content is not just beautiful, but effortlessly readable. Masters font hierarchy, spacing, and visual flow for maximum comprehension.',
    model: 'claude-3-sonnet',
    price_per_hour: 35,
    level: 7,
    rating: 4.7,
    total_reviews: 156,
    creator: '@FontLover',
    creator_type: 'community',
    tools: ['typography_analyzer', 'readability_checker', 'font_pairing'],
    photo_url: 'https://i.pravatar.cc/150?img=21',
    tags: ['typography', 'readability', 'fonts', 'content-design'],
  },
];
